// AUTO-GENERATED BY cxxbridge
#include "vtk_plane.h"

#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wmissing-declarations"
#ifdef __clang__
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#endif // __clang__
#endif // __GNUC__

using vtkPlane = ::vtkPlane;

extern "C" {
::vtkPlane *cxxbridge1$192$vtk_plane_new() noexcept {
  ::vtkPlane *(*vtk_plane_new$)() = ::vtk_plane_new;
  return vtk_plane_new$();
}

void cxxbridge1$192$vtk_plane_delete(::vtkPlane &plane) noexcept {
  void (*vtk_plane_delete$)(::vtkPlane &) = ::vtk_plane_delete;
  vtk_plane_delete$(plane);
}

void cxxbridge1$192$plane_set_origin(::vtkPlane &plane, double x, double y, double z) noexcept {
  void (*plane_set_origin$)(::vtkPlane &, double, double, double) = ::plane_set_origin;
  plane_set_origin$(plane, x, y, z);
}

void cxxbridge1$192$plane_get_origin(::vtkPlane const &plane, double *x, double *y, double *z) noexcept {
  void (*plane_get_origin$)(::vtkPlane const &, double *, double *, double *) = ::plane_get_origin;
  plane_get_origin$(plane, x, y, z);
}

void cxxbridge1$192$plane_set_normal(::vtkPlane &plane, double nx, double ny, double nz) noexcept {
  void (*plane_set_normal$)(::vtkPlane &, double, double, double) = ::plane_set_normal;
  plane_set_normal$(plane, nx, ny, nz);
}

void cxxbridge1$192$plane_get_normal(::vtkPlane const &plane, double *nx, double *ny, double *nz) noexcept {
  void (*plane_get_normal$)(::vtkPlane const &, double *, double *, double *) = ::plane_get_normal;
  plane_get_normal$(plane, nx, ny, nz);
}
} // extern "C"