// AUTO-GENERATED BY cxxbridge
#include "vtk_world_point_picker.h"
#include "vtk_renderer.h"
#include <cstdint>

#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wmissing-declarations"
#ifdef __clang__
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#endif // __clang__
#endif // __GNUC__

using vtkWorldPointPicker = ::vtkWorldPointPicker;
using vtkRenderer = ::vtkRenderer;

extern "C" {
::vtkWorldPointPicker *cxxbridge1$192$vtk_world_point_picker_new() noexcept {
  ::vtkWorldPointPicker *(*vtk_world_point_picker_new$)() = ::vtk_world_point_picker_new;
  return vtk_world_point_picker_new$();
}

void cxxbridge1$192$vtk_world_point_picker_delete(::vtkWorldPointPicker &picker) noexcept {
  void (*vtk_world_point_picker_delete$)(::vtkWorldPointPicker &) = ::vtk_world_point_picker_delete;
  vtk_world_point_picker_delete$(picker);
}

::std::int32_t cxxbridge1$192$vtk_world_point_picker_pick(::vtkWorldPointPicker &picker, double x, double y, double z, ::vtkRenderer *renderer) noexcept {
  ::std::int32_t (*vtk_world_point_picker_pick$)(::vtkWorldPointPicker &, double, double, double, ::vtkRenderer *) = ::vtk_world_point_picker_pick;
  return vtk_world_point_picker_pick$(picker, x, y, z, renderer);
}

void cxxbridge1$192$vtk_world_point_picker_get_pick_position(::vtkWorldPointPicker const &picker, double &x, double &y, double &z) noexcept {
  void (*vtk_world_point_picker_get_pick_position$)(::vtkWorldPointPicker const &, double &, double &, double &) = ::vtk_world_point_picker_get_pick_position;
  vtk_world_point_picker_get_pick_position$(picker, x, y, z);
}
} // extern "C"