// AUTO-GENERATED BY cxxbridge
#include "vtk_contour_filter.h"
#include "vtk_algorithm_output.h"
#include <cstdint>

#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wmissing-declarations"
#ifdef __clang__
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#endif // __clang__
#endif // __GNUC__

using vtkContourFilter = ::vtkContourFilter;
using vtkAlgorithmOutput = ::vtkAlgorithmOutput;
using vtkDataSet = ::vtkDataSet;

extern "C" {
::vtkContourFilter *cxxbridge1$192$vtk_contour_filter_new() noexcept {
  ::vtkContourFilter *(*vtk_contour_filter_new$)() = ::vtk_contour_filter_new;
  return vtk_contour_filter_new$();
}

void cxxbridge1$192$vtk_contour_filter_delete(::vtkContourFilter &filter) noexcept {
  void (*vtk_contour_filter_delete$)(::vtkContourFilter &) = ::vtk_contour_filter_delete;
  vtk_contour_filter_delete$(filter);
}

void cxxbridge1$192$contour_filter_set_input_connection(::vtkContourFilter &filter, ::vtkAlgorithmOutput *output) noexcept {
  void (*contour_filter_set_input_connection$)(::vtkContourFilter &, ::vtkAlgorithmOutput *) = ::contour_filter_set_input_connection;
  contour_filter_set_input_connection$(filter, output);
}

void cxxbridge1$192$contour_filter_set_input_data(::vtkContourFilter &filter, ::vtkDataSet *data_set) noexcept {
  void (*contour_filter_set_input_data$)(::vtkContourFilter &, ::vtkDataSet *) = ::contour_filter_set_input_data;
  contour_filter_set_input_data$(filter, data_set);
}

void cxxbridge1$192$contour_filter_set_value(::vtkContourFilter &filter, ::std::int32_t i, double value) noexcept {
  void (*contour_filter_set_value$)(::vtkContourFilter &, ::std::int32_t, double) = ::contour_filter_set_value;
  contour_filter_set_value$(filter, i, value);
}

void cxxbridge1$192$contour_filter_generate_values(::vtkContourFilter &filter, ::std::int32_t num_contours, double range_min, double range_max) noexcept {
  void (*contour_filter_generate_values$)(::vtkContourFilter &, ::std::int32_t, double, double) = ::contour_filter_generate_values;
  contour_filter_generate_values$(filter, num_contours, range_min, range_max);
}

::vtkAlgorithmOutput *cxxbridge1$192$contour_filter_get_output_port(::vtkContourFilter &filter) noexcept {
  ::vtkAlgorithmOutput *(*contour_filter_get_output_port$)(::vtkContourFilter &) = ::contour_filter_get_output_port;
  return contour_filter_get_output_port$(filter);
}
} // extern "C"