// AUTO-GENERATED BY cxxbridge
#include "vtk_shrink_filter.h"
#include "vtk_algorithm_output.h"

#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wmissing-declarations"
#ifdef __clang__
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#endif // __clang__
#endif // __GNUC__

using vtkShrinkFilter = ::vtkShrinkFilter;
using vtkAlgorithmOutput = ::vtkAlgorithmOutput;

extern "C" {
::vtkShrinkFilter *cxxbridge1$192$vtk_shrink_filter_new() noexcept {
  ::vtkShrinkFilter *(*vtk_shrink_filter_new$)() = ::vtk_shrink_filter_new;
  return vtk_shrink_filter_new$();
}

void cxxbridge1$192$vtk_shrink_filter_delete(::vtkShrinkFilter &f) noexcept {
  void (*vtk_shrink_filter_delete$)(::vtkShrinkFilter &) = ::vtk_shrink_filter_delete;
  vtk_shrink_filter_delete$(f);
}

void cxxbridge1$192$shrink_set_input_connection(::vtkShrinkFilter &f, ::vtkAlgorithmOutput *output) noexcept {
  void (*shrink_set_input_connection$)(::vtkShrinkFilter &, ::vtkAlgorithmOutput *) = ::shrink_set_input_connection;
  shrink_set_input_connection$(f, output);
}

void cxxbridge1$192$shrink_set_shrink_factor(::vtkShrinkFilter &f, double factor) noexcept {
  void (*shrink_set_shrink_factor$)(::vtkShrinkFilter &, double) = ::shrink_set_shrink_factor;
  shrink_set_shrink_factor$(f, factor);
}

double cxxbridge1$192$shrink_get_shrink_factor(::vtkShrinkFilter &f) noexcept {
  double (*shrink_get_shrink_factor$)(::vtkShrinkFilter &) = ::shrink_get_shrink_factor;
  return shrink_get_shrink_factor$(f);
}

::vtkAlgorithmOutput *cxxbridge1$192$shrink_get_output_port(::vtkShrinkFilter &f) noexcept {
  ::vtkAlgorithmOutput *(*shrink_get_output_port$)(::vtkShrinkFilter &) = ::shrink_get_output_port;
  return shrink_get_output_port$(f);
}
} // extern "C"