// AUTO-GENERATED BY cxxbridge
#include "vtk_smooth_poly_data_filter.h"
#include "vtk_algorithm_output.h"
#include <cstdint>

#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wmissing-declarations"
#ifdef __clang__
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#endif // __clang__
#endif // __GNUC__

using vtkSmoothPolyDataFilter = ::vtkSmoothPolyDataFilter;
using vtkAlgorithmOutput = ::vtkAlgorithmOutput;

extern "C" {
::vtkSmoothPolyDataFilter *cxxbridge1$192$vtk_smooth_poly_data_filter_new() noexcept {
  ::vtkSmoothPolyDataFilter *(*vtk_smooth_poly_data_filter_new$)() = ::vtk_smooth_poly_data_filter_new;
  return vtk_smooth_poly_data_filter_new$();
}

void cxxbridge1$192$vtk_smooth_poly_data_filter_delete(::vtkSmoothPolyDataFilter &filter) noexcept {
  void (*vtk_smooth_poly_data_filter_delete$)(::vtkSmoothPolyDataFilter &) = ::vtk_smooth_poly_data_filter_delete;
  vtk_smooth_poly_data_filter_delete$(filter);
}

void cxxbridge1$192$smooth_poly_data_filter_set_input_connection(::vtkSmoothPolyDataFilter &filter, ::vtkAlgorithmOutput *output) noexcept {
  void (*smooth_poly_data_filter_set_input_connection$)(::vtkSmoothPolyDataFilter &, ::vtkAlgorithmOutput *) = ::smooth_poly_data_filter_set_input_connection;
  smooth_poly_data_filter_set_input_connection$(filter, output);
}

void cxxbridge1$192$smooth_poly_data_filter_set_number_of_iterations(::vtkSmoothPolyDataFilter &filter, ::std::int32_t iterations) noexcept {
  void (*smooth_poly_data_filter_set_number_of_iterations$)(::vtkSmoothPolyDataFilter &, ::std::int32_t) = ::smooth_poly_data_filter_set_number_of_iterations;
  smooth_poly_data_filter_set_number_of_iterations$(filter, iterations);
}

::std::int32_t cxxbridge1$192$smooth_poly_data_filter_get_number_of_iterations(::vtkSmoothPolyDataFilter &filter) noexcept {
  ::std::int32_t (*smooth_poly_data_filter_get_number_of_iterations$)(::vtkSmoothPolyDataFilter &) = ::smooth_poly_data_filter_get_number_of_iterations;
  return smooth_poly_data_filter_get_number_of_iterations$(filter);
}

void cxxbridge1$192$smooth_poly_data_filter_set_relaxation_factor(::vtkSmoothPolyDataFilter &filter, double factor) noexcept {
  void (*smooth_poly_data_filter_set_relaxation_factor$)(::vtkSmoothPolyDataFilter &, double) = ::smooth_poly_data_filter_set_relaxation_factor;
  smooth_poly_data_filter_set_relaxation_factor$(filter, factor);
}

double cxxbridge1$192$smooth_poly_data_filter_get_relaxation_factor(::vtkSmoothPolyDataFilter &filter) noexcept {
  double (*smooth_poly_data_filter_get_relaxation_factor$)(::vtkSmoothPolyDataFilter &) = ::smooth_poly_data_filter_get_relaxation_factor;
  return smooth_poly_data_filter_get_relaxation_factor$(filter);
}

void cxxbridge1$192$smooth_poly_data_filter_set_feature_edge_smoothing(::vtkSmoothPolyDataFilter &filter, bool on) noexcept {
  void (*smooth_poly_data_filter_set_feature_edge_smoothing$)(::vtkSmoothPolyDataFilter &, bool) = ::smooth_poly_data_filter_set_feature_edge_smoothing;
  smooth_poly_data_filter_set_feature_edge_smoothing$(filter, on);
}

void cxxbridge1$192$smooth_poly_data_filter_set_boundary_smoothing(::vtkSmoothPolyDataFilter &filter, bool on) noexcept {
  void (*smooth_poly_data_filter_set_boundary_smoothing$)(::vtkSmoothPolyDataFilter &, bool) = ::smooth_poly_data_filter_set_boundary_smoothing;
  smooth_poly_data_filter_set_boundary_smoothing$(filter, on);
}

::vtkAlgorithmOutput *cxxbridge1$192$smooth_poly_data_filter_get_output_port(::vtkSmoothPolyDataFilter &filter) noexcept {
  ::vtkAlgorithmOutput *(*smooth_poly_data_filter_get_output_port$)(::vtkSmoothPolyDataFilter &) = ::smooth_poly_data_filter_get_output_port;
  return smooth_poly_data_filter_get_output_port$(filter);
}
} // extern "C"