// AUTO-GENERATED BY cxxbridge
#include "vtk_scalar_bar_actor.h"
#include <array>
#include <cstdint>
#include <new>
#include <string>
#if __cplusplus >= 201703L
#include <string_view>
#endif

#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wmissing-declarations"
#ifdef __clang__
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#endif // __clang__
#endif // __GNUC__

namespace rust {
inline namespace cxxbridge1 {
// #include "rust/cxx.h"

struct unsafe_bitcopy_t;

namespace {
template <typename T>
class impl;
} // namespace

#ifndef CXXBRIDGE1_RUST_STRING
#define CXXBRIDGE1_RUST_STRING
class String final {
public:
  String() noexcept;
  String(const String &) noexcept;
  String(String &&) noexcept;
  ~String() noexcept;

  String(const std::string &);
  String(const char *);
  String(const char *, std::size_t);
  String(const char16_t *);
  String(const char16_t *, std::size_t);
#ifdef __cpp_char8_t
  String(const char8_t *s);
  String(const char8_t *s, std::size_t len);
#endif

  static String lossy(const std::string &) noexcept;
  static String lossy(const char *) noexcept;
  static String lossy(const char *, std::size_t) noexcept;
  static String lossy(const char16_t *) noexcept;
  static String lossy(const char16_t *, std::size_t) noexcept;

  String &operator=(const String &) & noexcept;
  String &operator=(String &&) & noexcept;

  explicit operator std::string() const;

  const char *data() const noexcept;
  std::size_t size() const noexcept;
  std::size_t length() const noexcept;
  bool empty() const noexcept;

  const char *c_str() noexcept;

  std::size_t capacity() const noexcept;
  void reserve(size_t new_cap) noexcept;

  using iterator = char *;
  iterator begin() noexcept;
  iterator end() noexcept;

  using const_iterator = const char *;
  const_iterator begin() const noexcept;
  const_iterator end() const noexcept;
  const_iterator cbegin() const noexcept;
  const_iterator cend() const noexcept;

  bool operator==(const String &) const noexcept;
  bool operator!=(const String &) const noexcept;
  bool operator<(const String &) const noexcept;
  bool operator<=(const String &) const noexcept;
  bool operator>(const String &) const noexcept;
  bool operator>=(const String &) const noexcept;

  void swap(String &) noexcept;

  String(unsafe_bitcopy_t, const String &) noexcept;

private:
  struct lossy_t;
  String(lossy_t, const char *, std::size_t) noexcept;
  String(lossy_t, const char16_t *, std::size_t) noexcept;
  friend void swap(String &lhs, String &rhs) noexcept { lhs.swap(rhs); }

  std::array<std::uintptr_t, 3> repr;
};
#endif // CXXBRIDGE1_RUST_STRING

#ifndef CXXBRIDGE1_RUST_STR
#define CXXBRIDGE1_RUST_STR
class Str final {
public:
  Str() noexcept;
  Str(const String &) noexcept;
  Str(const std::string &);
  Str(const char *);
  Str(const char *, std::size_t);

  Str &operator=(const Str &) & noexcept = default;

  explicit operator std::string() const;
#if __cplusplus >= 201703L
  explicit operator std::string_view() const;
#endif

  const char *data() const noexcept;
  std::size_t size() const noexcept;
  std::size_t length() const noexcept;
  bool empty() const noexcept;

  Str(const Str &) noexcept = default;
  ~Str() noexcept = default;

  using iterator = const char *;
  using const_iterator = const char *;
  const_iterator begin() const noexcept;
  const_iterator end() const noexcept;
  const_iterator cbegin() const noexcept;
  const_iterator cend() const noexcept;

  bool operator==(const Str &) const noexcept;
  bool operator!=(const Str &) const noexcept;
  bool operator<(const Str &) const noexcept;
  bool operator<=(const Str &) const noexcept;
  bool operator>(const Str &) const noexcept;
  bool operator>=(const Str &) const noexcept;

  void swap(Str &) noexcept;

private:
  class uninit;
  Str(uninit) noexcept;
  friend impl<Str>;

  std::array<std::uintptr_t, 2> repr;
};
#endif // CXXBRIDGE1_RUST_STR
} // namespace cxxbridge1
} // namespace rust

using vtkScalarBarActor = ::vtkScalarBarActor;

extern "C" {
::vtkScalarBarActor *cxxbridge1$192$scalar_bar_actor_new() noexcept {
  ::vtkScalarBarActor *(*scalar_bar_actor_new$)() = ::scalar_bar_actor_new;
  return scalar_bar_actor_new$();
}

void cxxbridge1$192$scalar_bar_actor_delete(::vtkScalarBarActor &actor) noexcept {
  void (*scalar_bar_actor_delete$)(::vtkScalarBarActor &) = ::scalar_bar_actor_delete;
  scalar_bar_actor_delete$(actor);
}

void cxxbridge1$192$scalar_bar_actor_set_lookup_table(::vtkScalarBarActor &actor, ::vtkLookupTable &lut) noexcept {
  void (*scalar_bar_actor_set_lookup_table$)(::vtkScalarBarActor &, ::vtkLookupTable &) = ::scalar_bar_actor_set_lookup_table;
  scalar_bar_actor_set_lookup_table$(actor, lut);
}

void cxxbridge1$192$scalar_bar_actor_set_title(::vtkScalarBarActor &actor, ::rust::Str title) noexcept {
  void (*scalar_bar_actor_set_title$)(::vtkScalarBarActor &, ::rust::Str) = ::scalar_bar_actor_set_title;
  scalar_bar_actor_set_title$(actor, title);
}

void cxxbridge1$192$scalar_bar_actor_get_title(::vtkScalarBarActor &actor, ::rust::String *return$) noexcept {
  ::rust::String (*scalar_bar_actor_get_title$)(::vtkScalarBarActor &) = ::scalar_bar_actor_get_title;
  new (return$) ::rust::String(scalar_bar_actor_get_title$(actor));
}

void cxxbridge1$192$scalar_bar_actor_set_number_of_labels(::vtkScalarBarActor &actor, ::std::int32_t n) noexcept {
  void (*scalar_bar_actor_set_number_of_labels$)(::vtkScalarBarActor &, ::std::int32_t) = ::scalar_bar_actor_set_number_of_labels;
  scalar_bar_actor_set_number_of_labels$(actor, n);
}

::std::int32_t cxxbridge1$192$scalar_bar_actor_get_number_of_labels(::vtkScalarBarActor &actor) noexcept {
  ::std::int32_t (*scalar_bar_actor_get_number_of_labels$)(::vtkScalarBarActor &) = ::scalar_bar_actor_get_number_of_labels;
  return scalar_bar_actor_get_number_of_labels$(actor);
}

void cxxbridge1$192$scalar_bar_actor_set_position(::vtkScalarBarActor &actor, double x, double y) noexcept {
  void (*scalar_bar_actor_set_position$)(::vtkScalarBarActor &, double, double) = ::scalar_bar_actor_set_position;
  scalar_bar_actor_set_position$(actor, x, y);
}

void cxxbridge1$192$scalar_bar_actor_get_position(::vtkScalarBarActor &actor, double &x, double &y) noexcept {
  void (*scalar_bar_actor_get_position$)(::vtkScalarBarActor &, double &, double &) = ::scalar_bar_actor_get_position;
  scalar_bar_actor_get_position$(actor, x, y);
}

void cxxbridge1$192$scalar_bar_actor_set_width(::vtkScalarBarActor &actor, double width) noexcept {
  void (*scalar_bar_actor_set_width$)(::vtkScalarBarActor &, double) = ::scalar_bar_actor_set_width;
  scalar_bar_actor_set_width$(actor, width);
}

double cxxbridge1$192$scalar_bar_actor_get_width(::vtkScalarBarActor &actor) noexcept {
  double (*scalar_bar_actor_get_width$)(::vtkScalarBarActor &) = ::scalar_bar_actor_get_width;
  return scalar_bar_actor_get_width$(actor);
}

void cxxbridge1$192$scalar_bar_actor_set_height(::vtkScalarBarActor &actor, double height) noexcept {
  void (*scalar_bar_actor_set_height$)(::vtkScalarBarActor &, double) = ::scalar_bar_actor_set_height;
  scalar_bar_actor_set_height$(actor, height);
}

double cxxbridge1$192$scalar_bar_actor_get_height(::vtkScalarBarActor &actor) noexcept {
  double (*scalar_bar_actor_get_height$)(::vtkScalarBarActor &) = ::scalar_bar_actor_get_height;
  return scalar_bar_actor_get_height$(actor);
}

::vtkTextProperty *cxxbridge1$192$scalar_bar_actor_get_label_text_property(::vtkScalarBarActor &actor) noexcept {
  ::vtkTextProperty *(*scalar_bar_actor_get_label_text_property$)(::vtkScalarBarActor &) = ::scalar_bar_actor_get_label_text_property;
  return scalar_bar_actor_get_label_text_property$(actor);
}

::vtkTextProperty *cxxbridge1$192$scalar_bar_actor_get_title_text_property(::vtkScalarBarActor &actor) noexcept {
  ::vtkTextProperty *(*scalar_bar_actor_get_title_text_property$)(::vtkScalarBarActor &) = ::scalar_bar_actor_get_title_text_property;
  return scalar_bar_actor_get_title_text_property$(actor);
}

void cxxbridge1$192$scalar_bar_actor_set_orientation(::vtkScalarBarActor &actor, ::std::int32_t orientation) noexcept {
  void (*scalar_bar_actor_set_orientation$)(::vtkScalarBarActor &, ::std::int32_t) = ::scalar_bar_actor_set_orientation;
  scalar_bar_actor_set_orientation$(actor, orientation);
}

::std::int32_t cxxbridge1$192$scalar_bar_actor_get_orientation(::vtkScalarBarActor &actor) noexcept {
  ::std::int32_t (*scalar_bar_actor_get_orientation$)(::vtkScalarBarActor &) = ::scalar_bar_actor_get_orientation;
  return scalar_bar_actor_get_orientation$(actor);
}

void cxxbridge1$192$scalar_bar_actor_set_visibility(::vtkScalarBarActor &actor, bool visible) noexcept {
  void (*scalar_bar_actor_set_visibility$)(::vtkScalarBarActor &, bool) = ::scalar_bar_actor_set_visibility;
  scalar_bar_actor_set_visibility$(actor, visible);
}

bool cxxbridge1$192$scalar_bar_actor_get_visibility(::vtkScalarBarActor &actor) noexcept {
  bool (*scalar_bar_actor_get_visibility$)(::vtkScalarBarActor &) = ::scalar_bar_actor_get_visibility;
  return scalar_bar_actor_get_visibility$(actor);
}
} // extern "C"