// AUTO-GENERATED BY cxxbridge
#include "vtk_threshold.h"
#include "vtk_algorithm_output.h"
#include <cstdint>

#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wmissing-declarations"
#ifdef __clang__
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#endif // __clang__
#endif // __GNUC__

using vtkThreshold = ::vtkThreshold;
using vtkAlgorithmOutput = ::vtkAlgorithmOutput;
using vtkDataSet = ::vtkDataSet;

extern "C" {
::vtkThreshold *cxxbridge1$192$vtk_threshold_new() noexcept {
  ::vtkThreshold *(*vtk_threshold_new$)() = ::vtk_threshold_new;
  return vtk_threshold_new$();
}

void cxxbridge1$192$vtk_threshold_delete(::vtkThreshold &thr) noexcept {
  void (*vtk_threshold_delete$)(::vtkThreshold &) = ::vtk_threshold_delete;
  vtk_threshold_delete$(thr);
}

void cxxbridge1$192$threshold_set_input_connection(::vtkThreshold &thr, ::vtkAlgorithmOutput *output) noexcept {
  void (*threshold_set_input_connection$)(::vtkThreshold &, ::vtkAlgorithmOutput *) = ::threshold_set_input_connection;
  threshold_set_input_connection$(thr, output);
}

void cxxbridge1$192$threshold_set_input_data(::vtkThreshold &thr, ::vtkDataSet *data_set) noexcept {
  void (*threshold_set_input_data$)(::vtkThreshold &, ::vtkDataSet *) = ::threshold_set_input_data;
  threshold_set_input_data$(thr, data_set);
}

void cxxbridge1$192$threshold_set_lower_threshold(::vtkThreshold &thr, double value) noexcept {
  void (*threshold_set_lower_threshold$)(::vtkThreshold &, double) = ::threshold_set_lower_threshold;
  threshold_set_lower_threshold$(thr, value);
}

void cxxbridge1$192$threshold_set_upper_threshold(::vtkThreshold &thr, double value) noexcept {
  void (*threshold_set_upper_threshold$)(::vtkThreshold &, double) = ::threshold_set_upper_threshold;
  threshold_set_upper_threshold$(thr, value);
}

void cxxbridge1$192$threshold_set_threshold_between(::vtkThreshold &thr, double lower, double upper) noexcept {
  void (*threshold_set_threshold_between$)(::vtkThreshold &, double, double) = ::threshold_set_threshold_between;
  threshold_set_threshold_between$(thr, lower, upper);
}

void cxxbridge1$192$threshold_set_component_mode(::vtkThreshold &thr, ::std::int32_t mode) noexcept {
  void (*threshold_set_component_mode$)(::vtkThreshold &, ::std::int32_t) = ::threshold_set_component_mode;
  threshold_set_component_mode$(thr, mode);
}

void cxxbridge1$192$threshold_set_selected_component(::vtkThreshold &thr, ::std::int32_t comp) noexcept {
  void (*threshold_set_selected_component$)(::vtkThreshold &, ::std::int32_t) = ::threshold_set_selected_component;
  threshold_set_selected_component$(thr, comp);
}

::vtkAlgorithmOutput *cxxbridge1$192$threshold_get_output_port(::vtkThreshold &thr) noexcept {
  ::vtkAlgorithmOutput *(*threshold_get_output_port$)(::vtkThreshold &) = ::threshold_get_output_port;
  return threshold_get_output_port$(thr);
}
} // extern "C"