// AUTO-GENERATED BY cxxbridge
#include "vtk_legend_box_actor.h"
#include <array>
#include <cstdint>
#include <string>
#if __cplusplus >= 201703L
#include <string_view>
#endif

#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wmissing-declarations"
#ifdef __clang__
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#endif // __clang__
#endif // __GNUC__

namespace rust {
inline namespace cxxbridge1 {
// #include "rust/cxx.h"

namespace {
template <typename T>
class impl;
} // namespace

class String;

#ifndef CXXBRIDGE1_RUST_STR
#define CXXBRIDGE1_RUST_STR
class Str final {
public:
  Str() noexcept;
  Str(const String &) noexcept;
  Str(const std::string &);
  Str(const char *);
  Str(const char *, std::size_t);

  Str &operator=(const Str &) & noexcept = default;

  explicit operator std::string() const;
#if __cplusplus >= 201703L
  explicit operator std::string_view() const;
#endif

  const char *data() const noexcept;
  std::size_t size() const noexcept;
  std::size_t length() const noexcept;
  bool empty() const noexcept;

  Str(const Str &) noexcept = default;
  ~Str() noexcept = default;

  using iterator = const char *;
  using const_iterator = const char *;
  const_iterator begin() const noexcept;
  const_iterator end() const noexcept;
  const_iterator cbegin() const noexcept;
  const_iterator cend() const noexcept;

  bool operator==(const Str &) const noexcept;
  bool operator!=(const Str &) const noexcept;
  bool operator<(const Str &) const noexcept;
  bool operator<=(const Str &) const noexcept;
  bool operator>(const Str &) const noexcept;
  bool operator>=(const Str &) const noexcept;

  void swap(Str &) noexcept;

private:
  class uninit;
  Str(uninit) noexcept;
  friend impl<Str>;

  std::array<std::uintptr_t, 2> repr;
};
#endif // CXXBRIDGE1_RUST_STR
} // namespace cxxbridge1
} // namespace rust

using vtkLegendBoxActor = ::vtkLegendBoxActor;

extern "C" {
::vtkLegendBoxActor *cxxbridge1$192$legend_box_actor_new() noexcept {
  ::vtkLegendBoxActor *(*legend_box_actor_new$)() = ::legend_box_actor_new;
  return legend_box_actor_new$();
}

void cxxbridge1$192$legend_box_actor_delete(::vtkLegendBoxActor &actor) noexcept {
  void (*legend_box_actor_delete$)(::vtkLegendBoxActor &) = ::legend_box_actor_delete;
  legend_box_actor_delete$(actor);
}

void cxxbridge1$192$legend_box_actor_set_number_of_entries(::vtkLegendBoxActor &actor, ::std::int32_t n) noexcept {
  void (*legend_box_actor_set_number_of_entries$)(::vtkLegendBoxActor &, ::std::int32_t) = ::legend_box_actor_set_number_of_entries;
  legend_box_actor_set_number_of_entries$(actor, n);
}

::std::int32_t cxxbridge1$192$legend_box_actor_get_number_of_entries(::vtkLegendBoxActor &actor) noexcept {
  ::std::int32_t (*legend_box_actor_get_number_of_entries$)(::vtkLegendBoxActor &) = ::legend_box_actor_get_number_of_entries;
  return legend_box_actor_get_number_of_entries$(actor);
}

void cxxbridge1$192$legend_box_actor_set_entry_string(::vtkLegendBoxActor &actor, ::std::int32_t index, ::rust::Str label) noexcept {
  void (*legend_box_actor_set_entry_string$)(::vtkLegendBoxActor &, ::std::int32_t, ::rust::Str) = ::legend_box_actor_set_entry_string;
  legend_box_actor_set_entry_string$(actor, index, label);
}

void cxxbridge1$192$legend_box_actor_set_entry_color(::vtkLegendBoxActor &actor, ::std::int32_t index, double r, double g, double b) noexcept {
  void (*legend_box_actor_set_entry_color$)(::vtkLegendBoxActor &, ::std::int32_t, double, double, double) = ::legend_box_actor_set_entry_color;
  legend_box_actor_set_entry_color$(actor, index, r, g, b);
}

void cxxbridge1$192$legend_box_actor_set_position(::vtkLegendBoxActor &actor, double x, double y) noexcept {
  void (*legend_box_actor_set_position$)(::vtkLegendBoxActor &, double, double) = ::legend_box_actor_set_position;
  legend_box_actor_set_position$(actor, x, y);
}

void cxxbridge1$192$legend_box_actor_get_position(::vtkLegendBoxActor &actor, double &x, double &y) noexcept {
  void (*legend_box_actor_get_position$)(::vtkLegendBoxActor &, double &, double &) = ::legend_box_actor_get_position;
  legend_box_actor_get_position$(actor, x, y);
}

void cxxbridge1$192$legend_box_actor_set_position2(::vtkLegendBoxActor &actor, double x, double y) noexcept {
  void (*legend_box_actor_set_position2$)(::vtkLegendBoxActor &, double, double) = ::legend_box_actor_set_position2;
  legend_box_actor_set_position2$(actor, x, y);
}

void cxxbridge1$192$legend_box_actor_get_position2(::vtkLegendBoxActor &actor, double &x, double &y) noexcept {
  void (*legend_box_actor_get_position2$)(::vtkLegendBoxActor &, double &, double &) = ::legend_box_actor_get_position2;
  legend_box_actor_get_position2$(actor, x, y);
}

void cxxbridge1$192$legend_box_actor_set_border(::vtkLegendBoxActor &actor, bool border) noexcept {
  void (*legend_box_actor_set_border$)(::vtkLegendBoxActor &, bool) = ::legend_box_actor_set_border;
  legend_box_actor_set_border$(actor, border);
}

bool cxxbridge1$192$legend_box_actor_get_border(::vtkLegendBoxActor &actor) noexcept {
  bool (*legend_box_actor_get_border$)(::vtkLegendBoxActor &) = ::legend_box_actor_get_border;
  return legend_box_actor_get_border$(actor);
}

void cxxbridge1$192$legend_box_actor_set_box(::vtkLegendBoxActor &actor, bool box_) noexcept {
  void (*legend_box_actor_set_box$)(::vtkLegendBoxActor &, bool) = ::legend_box_actor_set_box;
  legend_box_actor_set_box$(actor, box_);
}

bool cxxbridge1$192$legend_box_actor_get_box(::vtkLegendBoxActor &actor) noexcept {
  bool (*legend_box_actor_get_box$)(::vtkLegendBoxActor &) = ::legend_box_actor_get_box;
  return legend_box_actor_get_box$(actor);
}

void cxxbridge1$192$legend_box_actor_set_padding(::vtkLegendBoxActor &actor, ::std::int32_t padding) noexcept {
  void (*legend_box_actor_set_padding$)(::vtkLegendBoxActor &, ::std::int32_t) = ::legend_box_actor_set_padding;
  legend_box_actor_set_padding$(actor, padding);
}

::std::int32_t cxxbridge1$192$legend_box_actor_get_padding(::vtkLegendBoxActor &actor) noexcept {
  ::std::int32_t (*legend_box_actor_get_padding$)(::vtkLegendBoxActor &) = ::legend_box_actor_get_padding;
  return legend_box_actor_get_padding$(actor);
}

void cxxbridge1$192$legend_box_actor_set_visibility(::vtkLegendBoxActor &actor, bool visible) noexcept {
  void (*legend_box_actor_set_visibility$)(::vtkLegendBoxActor &, bool) = ::legend_box_actor_set_visibility;
  legend_box_actor_set_visibility$(actor, visible);
}

bool cxxbridge1$192$legend_box_actor_get_visibility(::vtkLegendBoxActor &actor) noexcept {
  bool (*legend_box_actor_get_visibility$)(::vtkLegendBoxActor &) = ::legend_box_actor_get_visibility;
  return legend_box_actor_get_visibility$(actor);
}
} // extern "C"