// AUTO-GENERATED BY cxxbridge
#include "vtk_actor.h"
#include "vtk_mapper.h"

#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wmissing-declarations"
#ifdef __clang__
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#endif // __clang__
#endif // __GNUC__

using vtkActor = ::vtkActor;
using vtkMapper = ::vtkMapper;
using vtkProperty = ::vtkProperty;

extern "C" {
::vtkActor *cxxbridge1$192$actor_new() noexcept {
  ::vtkActor *(*actor_new$)() = ::actor_new;
  return actor_new$();
}

void cxxbridge1$192$actor_delete(::vtkActor &actor) noexcept {
  void (*actor_delete$)(::vtkActor &) = ::actor_delete;
  actor_delete$(actor);
}

void cxxbridge1$192$actor_set_mapper(::vtkActor &actor, ::vtkMapper *mapper) noexcept {
  void (*actor_set_mapper$)(::vtkActor &, ::vtkMapper *) = ::actor_set_mapper;
  actor_set_mapper$(actor, mapper);
}

::vtkProperty *cxxbridge1$192$actor_get_property(::vtkActor &actor) noexcept {
  ::vtkProperty *(*actor_get_property$)(::vtkActor &) = ::actor_get_property;
  return actor_get_property$(actor);
}

void cxxbridge1$192$actor_set_position(::vtkActor &actor, double x, double y, double z) noexcept {
  void (*actor_set_position$)(::vtkActor &, double, double, double) = ::actor_set_position;
  actor_set_position$(actor, x, y, z);
}

void cxxbridge1$192$actor_get_position(::vtkActor const &actor, double &x, double &y, double &z) noexcept {
  void (*actor_get_position$)(::vtkActor const &, double &, double &, double &) = ::actor_get_position;
  actor_get_position$(actor, x, y, z);
}

void cxxbridge1$192$actor_add_position(::vtkActor &actor, double x, double y, double z) noexcept {
  void (*actor_add_position$)(::vtkActor &, double, double, double) = ::actor_add_position;
  actor_add_position$(actor, x, y, z);
}

void cxxbridge1$192$actor_rotate_x(::vtkActor &actor, double angle) noexcept {
  void (*actor_rotate_x$)(::vtkActor &, double) = ::actor_rotate_x;
  actor_rotate_x$(actor, angle);
}

void cxxbridge1$192$actor_rotate_y(::vtkActor &actor, double angle) noexcept {
  void (*actor_rotate_y$)(::vtkActor &, double) = ::actor_rotate_y;
  actor_rotate_y$(actor, angle);
}

void cxxbridge1$192$actor_rotate_z(::vtkActor &actor, double angle) noexcept {
  void (*actor_rotate_z$)(::vtkActor &, double) = ::actor_rotate_z;
  actor_rotate_z$(actor, angle);
}

void cxxbridge1$192$actor_set_orientation(::vtkActor &actor, double x, double y, double z) noexcept {
  void (*actor_set_orientation$)(::vtkActor &, double, double, double) = ::actor_set_orientation;
  actor_set_orientation$(actor, x, y, z);
}

void cxxbridge1$192$actor_get_orientation(::vtkActor const &actor, double &x, double &y, double &z) noexcept {
  void (*actor_get_orientation$)(::vtkActor const &, double &, double &, double &) = ::actor_get_orientation;
  actor_get_orientation$(actor, x, y, z);
}

void cxxbridge1$192$actor_set_scale(::vtkActor &actor, double x, double y, double z) noexcept {
  void (*actor_set_scale$)(::vtkActor &, double, double, double) = ::actor_set_scale;
  actor_set_scale$(actor, x, y, z);
}

void cxxbridge1$192$actor_get_scale(::vtkActor const &actor, double &x, double &y, double &z) noexcept {
  void (*actor_get_scale$)(::vtkActor const &, double &, double &, double &) = ::actor_get_scale;
  actor_get_scale$(actor, x, y, z);
}

void cxxbridge1$192$actor_set_visibility(::vtkActor &actor, bool visible) noexcept {
  void (*actor_set_visibility$)(::vtkActor &, bool) = ::actor_set_visibility;
  actor_set_visibility$(actor, visible);
}

bool cxxbridge1$192$actor_get_visibility(::vtkActor const &actor) noexcept {
  bool (*actor_get_visibility$)(::vtkActor const &) = ::actor_get_visibility;
  return actor_get_visibility$(actor);
}

void cxxbridge1$192$actor_set_pickable(::vtkActor &actor, bool pickable) noexcept {
  void (*actor_set_pickable$)(::vtkActor &, bool) = ::actor_set_pickable;
  actor_set_pickable$(actor, pickable);
}

bool cxxbridge1$192$actor_get_pickable(::vtkActor const &actor) noexcept {
  bool (*actor_get_pickable$)(::vtkActor const &) = ::actor_get_pickable;
  return actor_get_pickable$(actor);
}
} // extern "C"