// AUTO-GENERATED BY cxxbridge
#include "vtk_lookup_table.h"
#include <cstdint>

#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wmissing-declarations"
#ifdef __clang__
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#endif // __clang__
#endif // __GNUC__

using vtkLookupTable = ::vtkLookupTable;

extern "C" {
::vtkLookupTable *cxxbridge1$192$lookup_table_new() noexcept {
  ::vtkLookupTable *(*lookup_table_new$)() = ::lookup_table_new;
  return lookup_table_new$();
}

void cxxbridge1$192$lookup_table_delete(::vtkLookupTable &lut) noexcept {
  void (*lookup_table_delete$)(::vtkLookupTable &) = ::lookup_table_delete;
  lookup_table_delete$(lut);
}

void cxxbridge1$192$lookup_table_set_range(::vtkLookupTable &lut, double min, double max) noexcept {
  void (*lookup_table_set_range$)(::vtkLookupTable &, double, double) = ::lookup_table_set_range;
  lookup_table_set_range$(lut, min, max);
}

void cxxbridge1$192$lookup_table_get_range(::vtkLookupTable &lut, double &min, double &max) noexcept {
  void (*lookup_table_get_range$)(::vtkLookupTable &, double &, double &) = ::lookup_table_get_range;
  lookup_table_get_range$(lut, min, max);
}

void cxxbridge1$192$lookup_table_set_hue_range(::vtkLookupTable &lut, double min, double max) noexcept {
  void (*lookup_table_set_hue_range$)(::vtkLookupTable &, double, double) = ::lookup_table_set_hue_range;
  lookup_table_set_hue_range$(lut, min, max);
}

void cxxbridge1$192$lookup_table_get_hue_range(::vtkLookupTable &lut, double &min, double &max) noexcept {
  void (*lookup_table_get_hue_range$)(::vtkLookupTable &, double &, double &) = ::lookup_table_get_hue_range;
  lookup_table_get_hue_range$(lut, min, max);
}

void cxxbridge1$192$lookup_table_set_saturation_range(::vtkLookupTable &lut, double min, double max) noexcept {
  void (*lookup_table_set_saturation_range$)(::vtkLookupTable &, double, double) = ::lookup_table_set_saturation_range;
  lookup_table_set_saturation_range$(lut, min, max);
}

void cxxbridge1$192$lookup_table_get_saturation_range(::vtkLookupTable &lut, double &min, double &max) noexcept {
  void (*lookup_table_get_saturation_range$)(::vtkLookupTable &, double &, double &) = ::lookup_table_get_saturation_range;
  lookup_table_get_saturation_range$(lut, min, max);
}

void cxxbridge1$192$lookup_table_set_value_range(::vtkLookupTable &lut, double min, double max) noexcept {
  void (*lookup_table_set_value_range$)(::vtkLookupTable &, double, double) = ::lookup_table_set_value_range;
  lookup_table_set_value_range$(lut, min, max);
}

void cxxbridge1$192$lookup_table_get_value_range(::vtkLookupTable &lut, double &min, double &max) noexcept {
  void (*lookup_table_get_value_range$)(::vtkLookupTable &, double &, double &) = ::lookup_table_get_value_range;
  lookup_table_get_value_range$(lut, min, max);
}

void cxxbridge1$192$lookup_table_set_alpha_range(::vtkLookupTable &lut, double min, double max) noexcept {
  void (*lookup_table_set_alpha_range$)(::vtkLookupTable &, double, double) = ::lookup_table_set_alpha_range;
  lookup_table_set_alpha_range$(lut, min, max);
}

void cxxbridge1$192$lookup_table_get_alpha_range(::vtkLookupTable &lut, double &min, double &max) noexcept {
  void (*lookup_table_get_alpha_range$)(::vtkLookupTable &, double &, double &) = ::lookup_table_get_alpha_range;
  lookup_table_get_alpha_range$(lut, min, max);
}

void cxxbridge1$192$lookup_table_set_number_of_table_values(::vtkLookupTable &lut, ::std::int64_t n) noexcept {
  void (*lookup_table_set_number_of_table_values$)(::vtkLookupTable &, ::std::int64_t) = ::lookup_table_set_number_of_table_values;
  lookup_table_set_number_of_table_values$(lut, n);
}

::std::int64_t cxxbridge1$192$lookup_table_get_number_of_table_values(::vtkLookupTable &lut) noexcept {
  ::std::int64_t (*lookup_table_get_number_of_table_values$)(::vtkLookupTable &) = ::lookup_table_get_number_of_table_values;
  return lookup_table_get_number_of_table_values$(lut);
}

void cxxbridge1$192$lookup_table_build(::vtkLookupTable &lut) noexcept {
  void (*lookup_table_build$)(::vtkLookupTable &) = ::lookup_table_build;
  lookup_table_build$(lut);
}

void cxxbridge1$192$lookup_table_get_color(::vtkLookupTable &lut, double value, double &r, double &g, double &b) noexcept {
  void (*lookup_table_get_color$)(::vtkLookupTable &, double, double &, double &, double &) = ::lookup_table_get_color;
  lookup_table_get_color$(lut, value, r, g, b);
}
} // extern "C"