// AUTO-GENERATED BY cxxbridge
#include "vtk_image_data.h"
#include "vtk_algorithm_output.h"
#include <cstdint>

#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wmissing-declarations"
#ifdef __clang__
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#endif // __clang__
#endif // __GNUC__

using vtkImageData = ::vtkImageData;
using vtkAlgorithmOutput = ::vtkAlgorithmOutput;

extern "C" {
::vtkImageData *cxxbridge1$192$vtk_image_data_new() noexcept {
  ::vtkImageData *(*vtk_image_data_new$)() = ::vtk_image_data_new;
  return vtk_image_data_new$();
}

void cxxbridge1$192$vtk_image_data_delete(::vtkImageData &image_data) noexcept {
  void (*vtk_image_data_delete$)(::vtkImageData &) = ::vtk_image_data_delete;
  vtk_image_data_delete$(image_data);
}

void cxxbridge1$192$image_data_set_dimensions(::vtkImageData &image_data, ::std::int32_t nx, ::std::int32_t ny, ::std::int32_t nz) noexcept {
  void (*image_data_set_dimensions$)(::vtkImageData &, ::std::int32_t, ::std::int32_t, ::std::int32_t) = ::image_data_set_dimensions;
  image_data_set_dimensions$(image_data, nx, ny, nz);
}

void cxxbridge1$192$image_data_get_dimensions(::vtkImageData const &image_data, ::std::int32_t *nx, ::std::int32_t *ny, ::std::int32_t *nz) noexcept {
  void (*image_data_get_dimensions$)(::vtkImageData const &, ::std::int32_t *, ::std::int32_t *, ::std::int32_t *) = ::image_data_get_dimensions;
  image_data_get_dimensions$(image_data, nx, ny, nz);
}

void cxxbridge1$192$image_data_set_spacing(::vtkImageData &image_data, double dx, double dy, double dz) noexcept {
  void (*image_data_set_spacing$)(::vtkImageData &, double, double, double) = ::image_data_set_spacing;
  image_data_set_spacing$(image_data, dx, dy, dz);
}

void cxxbridge1$192$image_data_get_spacing(::vtkImageData const &image_data, double *dx, double *dy, double *dz) noexcept {
  void (*image_data_get_spacing$)(::vtkImageData const &, double *, double *, double *) = ::image_data_get_spacing;
  image_data_get_spacing$(image_data, dx, dy, dz);
}

void cxxbridge1$192$image_data_set_origin(::vtkImageData &image_data, double x, double y, double z) noexcept {
  void (*image_data_set_origin$)(::vtkImageData &, double, double, double) = ::image_data_set_origin;
  image_data_set_origin$(image_data, x, y, z);
}

void cxxbridge1$192$image_data_get_origin(::vtkImageData const &image_data, double *x, double *y, double *z) noexcept {
  void (*image_data_get_origin$)(::vtkImageData const &, double *, double *, double *) = ::image_data_get_origin;
  image_data_get_origin$(image_data, x, y, z);
}

void cxxbridge1$192$image_data_allocate_scalars(::vtkImageData &image_data, ::std::int32_t vtk_type, ::std::int32_t num_components) noexcept {
  void (*image_data_allocate_scalars$)(::vtkImageData &, ::std::int32_t, ::std::int32_t) = ::image_data_allocate_scalars;
  image_data_allocate_scalars$(image_data, vtk_type, num_components);
}

void cxxbridge1$192$image_data_set_scalar_component_from_double(::vtkImageData &image_data, ::std::int32_t x, ::std::int32_t y, ::std::int32_t z, ::std::int32_t component, double value) noexcept {
  void (*image_data_set_scalar_component_from_double$)(::vtkImageData &, ::std::int32_t, ::std::int32_t, ::std::int32_t, ::std::int32_t, double) = ::image_data_set_scalar_component_from_double;
  image_data_set_scalar_component_from_double$(image_data, x, y, z, component, value);
}

double cxxbridge1$192$image_data_get_scalar_component_as_double(::vtkImageData const &image_data, ::std::int32_t x, ::std::int32_t y, ::std::int32_t z, ::std::int32_t component) noexcept {
  double (*image_data_get_scalar_component_as_double$)(::vtkImageData const &, ::std::int32_t, ::std::int32_t, ::std::int32_t, ::std::int32_t) = ::image_data_get_scalar_component_as_double;
  return image_data_get_scalar_component_as_double$(image_data, x, y, z, component);
}

::std::int32_t cxxbridge1$192$image_data_get_number_of_points(::vtkImageData const &image_data) noexcept {
  ::std::int32_t (*image_data_get_number_of_points$)(::vtkImageData const &) = ::image_data_get_number_of_points;
  return image_data_get_number_of_points$(image_data);
}

::std::int32_t cxxbridge1$192$image_data_get_number_of_cells(::vtkImageData const &image_data) noexcept {
  ::std::int32_t (*image_data_get_number_of_cells$)(::vtkImageData const &) = ::image_data_get_number_of_cells;
  return image_data_get_number_of_cells$(image_data);
}

void cxxbridge1$192$image_data_get_bounds(::vtkImageData const &image_data, double *bounds) noexcept {
  void (*image_data_get_bounds$)(::vtkImageData const &, double *) = ::image_data_get_bounds;
  image_data_get_bounds$(image_data, bounds);
}
} // extern "C"