// AUTO-GENERATED BY cxxbridge
#include "vtk_renderer.h"
#include "vtk_actor.h"

#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wmissing-declarations"
#ifdef __clang__
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#endif // __clang__
#endif // __GNUC__

using vtkRenderer = ::vtkRenderer;
using vtkActor = ::vtkActor;
using vtkActor2D = ::vtkActor2D;
using vtkCamera = ::vtkCamera;

extern "C" {
::vtkRenderer *cxxbridge1$192$renderer_new() noexcept {
  ::vtkRenderer *(*renderer_new$)() = ::renderer_new;
  return renderer_new$();
}

void cxxbridge1$192$renderer_delete(::vtkRenderer &renderer) noexcept {
  void (*renderer_delete$)(::vtkRenderer &) = ::renderer_delete;
  renderer_delete$(renderer);
}

void cxxbridge1$192$renderer_add_actor(::vtkRenderer &renderer, ::vtkActor *actor) noexcept {
  void (*renderer_add_actor$)(::vtkRenderer &, ::vtkActor *) = ::renderer_add_actor;
  renderer_add_actor$(renderer, actor);
}

void cxxbridge1$192$renderer_add_actor2d(::vtkRenderer &renderer, ::vtkActor2D *actor) noexcept {
  void (*renderer_add_actor2d$)(::vtkRenderer &, ::vtkActor2D *) = ::renderer_add_actor2d;
  renderer_add_actor2d$(renderer, actor);
}

void cxxbridge1$192$renderer_set_background(::vtkRenderer &renderer, double r, double g, double b) noexcept {
  void (*renderer_set_background$)(::vtkRenderer &, double, double, double) = ::renderer_set_background;
  renderer_set_background$(renderer, r, g, b);
}

::vtkCamera *cxxbridge1$192$renderer_get_active_camera(::vtkRenderer &renderer) noexcept {
  ::vtkCamera *(*renderer_get_active_camera$)(::vtkRenderer &) = ::renderer_get_active_camera;
  return renderer_get_active_camera$(renderer);
}

void cxxbridge1$192$renderer_reset_camera(::vtkRenderer &renderer) noexcept {
  void (*renderer_reset_camera$)(::vtkRenderer &) = ::renderer_reset_camera;
  renderer_reset_camera$(renderer);
}

void cxxbridge1$192$renderer_set_display_point(::vtkRenderer &renderer, double x, double y, double z) noexcept {
  void (*renderer_set_display_point$)(::vtkRenderer &, double, double, double) = ::renderer_set_display_point;
  renderer_set_display_point$(renderer, x, y, z);
}

void cxxbridge1$192$renderer_display_to_world(::vtkRenderer &renderer) noexcept {
  void (*renderer_display_to_world$)(::vtkRenderer &) = ::renderer_display_to_world;
  renderer_display_to_world$(renderer);
}

void cxxbridge1$192$renderer_get_world_point(::vtkRenderer &renderer, double &x, double &y, double &z, double &w) noexcept {
  void (*renderer_get_world_point$)(::vtkRenderer &, double &, double &, double &, double &) = ::renderer_get_world_point;
  renderer_get_world_point$(renderer, x, y, z, w);
}

void cxxbridge1$192$renderer_set_world_point(::vtkRenderer &renderer, double x, double y, double z, double w) noexcept {
  void (*renderer_set_world_point$)(::vtkRenderer &, double, double, double, double) = ::renderer_set_world_point;
  renderer_set_world_point$(renderer, x, y, z, w);
}

void cxxbridge1$192$renderer_world_to_display(::vtkRenderer &renderer) noexcept {
  void (*renderer_world_to_display$)(::vtkRenderer &) = ::renderer_world_to_display;
  renderer_world_to_display$(renderer);
}

void cxxbridge1$192$renderer_get_display_point(::vtkRenderer &renderer, double &x, double &y, double &z) noexcept {
  void (*renderer_get_display_point$)(::vtkRenderer &, double &, double &, double &) = ::renderer_get_display_point;
  renderer_get_display_point$(renderer, x, y, z);
}
} // extern "C"