// AUTO-GENERATED BY cxxbridge
#include "vtk_clip_poly_data.h"
#include "vtk_algorithm_output.h"
#include "vtk_plane.h"

#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wmissing-declarations"
#ifdef __clang__
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#endif // __clang__
#endif // __GNUC__

using vtkClipPolyData = ::vtkClipPolyData;
using vtkAlgorithmOutput = ::vtkAlgorithmOutput;
using vtkPlane = ::vtkPlane;

extern "C" {
::vtkClipPolyData *cxxbridge1$192$vtk_clip_poly_data_new() noexcept {
  ::vtkClipPolyData *(*vtk_clip_poly_data_new$)() = ::vtk_clip_poly_data_new;
  return vtk_clip_poly_data_new$();
}

void cxxbridge1$192$vtk_clip_poly_data_delete(::vtkClipPolyData &clipper) noexcept {
  void (*vtk_clip_poly_data_delete$)(::vtkClipPolyData &) = ::vtk_clip_poly_data_delete;
  vtk_clip_poly_data_delete$(clipper);
}

void cxxbridge1$192$clip_poly_data_set_input_connection(::vtkClipPolyData &clipper, ::vtkAlgorithmOutput *output) noexcept {
  void (*clip_poly_data_set_input_connection$)(::vtkClipPolyData &, ::vtkAlgorithmOutput *) = ::clip_poly_data_set_input_connection;
  clip_poly_data_set_input_connection$(clipper, output);
}

void cxxbridge1$192$clip_poly_data_set_clip_function(::vtkClipPolyData &clipper, ::vtkPlane *plane) noexcept {
  void (*clip_poly_data_set_clip_function$)(::vtkClipPolyData &, ::vtkPlane *) = ::clip_poly_data_set_clip_function;
  clip_poly_data_set_clip_function$(clipper, plane);
}

void cxxbridge1$192$clip_poly_data_set_value(::vtkClipPolyData &clipper, double value) noexcept {
  void (*clip_poly_data_set_value$)(::vtkClipPolyData &, double) = ::clip_poly_data_set_value;
  clip_poly_data_set_value$(clipper, value);
}

::vtkAlgorithmOutput *cxxbridge1$192$clip_poly_data_get_output_port(::vtkClipPolyData &clipper) noexcept {
  ::vtkAlgorithmOutput *(*clip_poly_data_get_output_port$)(::vtkClipPolyData &) = ::clip_poly_data_get_output_port;
  return clip_poly_data_get_output_port$(clipper);
}
} // extern "C"