// AUTO-GENERATED BY cxxbridge
#include "vtk_warp_vector.h"
#include "vtk_algorithm_output.h"

#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wmissing-declarations"
#ifdef __clang__
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#endif // __clang__
#endif // __GNUC__

using vtkWarpVector = ::vtkWarpVector;
using vtkAlgorithmOutput = ::vtkAlgorithmOutput;
using vtkDataSet = ::vtkDataSet;

extern "C" {
::vtkWarpVector *cxxbridge1$192$vtk_warp_vector_new() noexcept {
  ::vtkWarpVector *(*vtk_warp_vector_new$)() = ::vtk_warp_vector_new;
  return vtk_warp_vector_new$();
}

void cxxbridge1$192$vtk_warp_vector_delete(::vtkWarpVector &warp) noexcept {
  void (*vtk_warp_vector_delete$)(::vtkWarpVector &) = ::vtk_warp_vector_delete;
  vtk_warp_vector_delete$(warp);
}

void cxxbridge1$192$warp_vector_set_input_connection(::vtkWarpVector &warp, ::vtkAlgorithmOutput *port) noexcept {
  void (*warp_vector_set_input_connection$)(::vtkWarpVector &, ::vtkAlgorithmOutput *) = ::warp_vector_set_input_connection;
  warp_vector_set_input_connection$(warp, port);
}

void cxxbridge1$192$warp_vector_set_input_data(::vtkWarpVector &warp, ::vtkDataSet *dataset) noexcept {
  void (*warp_vector_set_input_data$)(::vtkWarpVector &, ::vtkDataSet *) = ::warp_vector_set_input_data;
  warp_vector_set_input_data$(warp, dataset);
}

void cxxbridge1$192$warp_vector_set_scale_factor(::vtkWarpVector &warp, double scale) noexcept {
  void (*warp_vector_set_scale_factor$)(::vtkWarpVector &, double) = ::warp_vector_set_scale_factor;
  warp_vector_set_scale_factor$(warp, scale);
}

double cxxbridge1$192$warp_vector_get_scale_factor(::vtkWarpVector &warp) noexcept {
  double (*warp_vector_get_scale_factor$)(::vtkWarpVector &) = ::warp_vector_get_scale_factor;
  return warp_vector_get_scale_factor$(warp);
}

::vtkAlgorithmOutput *cxxbridge1$192$warp_vector_get_output_port(::vtkWarpVector &warp) noexcept {
  ::vtkAlgorithmOutput *(*warp_vector_get_output_port$)(::vtkWarpVector &) = ::warp_vector_get_output_port;
  return warp_vector_get_output_port$(warp);
}
} // extern "C"