// AUTO-GENERATED BY cxxbridge
#include "vtk_render_window.h"
#include "vtk_renderer.h"
#include "vtk_command.h"
#include <array>
#include <cstddef>
#include <cstdint>
#include <string>
#if __cplusplus >= 201703L
#include <string_view>
#endif

#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wmissing-declarations"
#ifdef __clang__
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#endif // __clang__
#endif // __GNUC__

namespace rust {
inline namespace cxxbridge1 {
// #include "rust/cxx.h"

namespace {
template <typename T>
class impl;
} // namespace

class String;

#ifndef CXXBRIDGE1_RUST_STR
#define CXXBRIDGE1_RUST_STR
class Str final {
public:
  Str() noexcept;
  Str(const String &) noexcept;
  Str(const std::string &);
  Str(const char *);
  Str(const char *, std::size_t);

  Str &operator=(const Str &) & noexcept = default;

  explicit operator std::string() const;
#if __cplusplus >= 201703L
  explicit operator std::string_view() const;
#endif

  const char *data() const noexcept;
  std::size_t size() const noexcept;
  std::size_t length() const noexcept;
  bool empty() const noexcept;

  Str(const Str &) noexcept = default;
  ~Str() noexcept = default;

  using iterator = const char *;
  using const_iterator = const char *;
  const_iterator begin() const noexcept;
  const_iterator end() const noexcept;
  const_iterator cbegin() const noexcept;
  const_iterator cend() const noexcept;

  bool operator==(const Str &) const noexcept;
  bool operator!=(const Str &) const noexcept;
  bool operator<(const Str &) const noexcept;
  bool operator<=(const Str &) const noexcept;
  bool operator>(const Str &) const noexcept;
  bool operator>=(const Str &) const noexcept;

  void swap(Str &) noexcept;

private:
  class uninit;
  Str(uninit) noexcept;
  friend impl<Str>;

  std::array<std::uintptr_t, 2> repr;
};
#endif // CXXBRIDGE1_RUST_STR
} // namespace cxxbridge1
} // namespace rust

using vtkRenderWindow = ::vtkRenderWindow;
using vtkRenderer = ::vtkRenderer;
using vtkCommand = ::vtkCommand;

extern "C" {
::vtkRenderWindow *cxxbridge1$192$render_window_new() noexcept {
  ::vtkRenderWindow *(*render_window_new$)() = ::render_window_new;
  return render_window_new$();
}

void cxxbridge1$192$render_window_delete(::vtkRenderWindow &window) noexcept {
  void (*render_window_delete$)(::vtkRenderWindow &) = ::render_window_delete;
  render_window_delete$(window);
}

void cxxbridge1$192$render_window_add_renderer(::vtkRenderWindow &window, ::vtkRenderer *renderer) noexcept {
  void (*render_window_add_renderer$)(::vtkRenderWindow &, ::vtkRenderer *) = ::render_window_add_renderer;
  render_window_add_renderer$(window, renderer);
}

void cxxbridge1$192$render_window_set_size(::vtkRenderWindow &window, ::std::int32_t width, ::std::int32_t height) noexcept {
  void (*render_window_set_size$)(::vtkRenderWindow &, ::std::int32_t, ::std::int32_t) = ::render_window_set_size;
  render_window_set_size$(window, width, height);
}

void cxxbridge1$192$render_window_set_window_name(::vtkRenderWindow &window, ::rust::Str name) noexcept {
  void (*render_window_set_window_name$)(::vtkRenderWindow &, ::rust::Str) = ::render_window_set_window_name;
  render_window_set_window_name$(window, name);
}

void cxxbridge1$192$render_window_render(::vtkRenderWindow &window) noexcept {
  void (*render_window_render$)(::vtkRenderWindow &) = ::render_window_render;
  render_window_render$(window);
}

void cxxbridge1$192$render_window_get_size(::vtkRenderWindow &window, ::std::int32_t &width, ::std::int32_t &height) noexcept {
  void (*render_window_get_size$)(::vtkRenderWindow &, ::std::int32_t &, ::std::int32_t &) = ::render_window_get_size;
  render_window_get_size$(window, width, height);
}

void cxxbridge1$192$render_window_get_pixel_data(::vtkRenderWindow &window, ::std::uint8_t *data, ::std::int32_t size) noexcept {
  void (*render_window_get_pixel_data$)(::vtkRenderWindow &, ::std::uint8_t *, ::std::int32_t) = ::render_window_get_pixel_data;
  render_window_get_pixel_data$(window, data, size);
}

void cxxbridge1$192$render_window_set_pixel_data(::vtkRenderWindow &window, ::std::uint8_t const *data, ::std::int32_t size) noexcept {
  void (*render_window_set_pixel_data$)(::vtkRenderWindow &, ::std::uint8_t const *, ::std::int32_t) = ::render_window_set_pixel_data;
  render_window_set_pixel_data$(window, data, size);
}

::std::size_t cxxbridge1$192$render_window_add_observer(::vtkRenderWindow &window, ::std::size_t event, ::vtkCommand *command) noexcept {
  ::std::size_t (*render_window_add_observer$)(::vtkRenderWindow &, ::std::size_t, ::vtkCommand *) = ::render_window_add_observer;
  return render_window_add_observer$(window, event, command);
}
} // extern "C"