// AUTO-GENERATED BY cxxbridge
#include "vtk_text_actor.h"
#include "vtk_render_window.h"
#include <array>
#include <cstdint>
#include <new>
#include <string>

#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wmissing-declarations"
#ifdef __clang__
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#endif // __clang__
#endif // __GNUC__

namespace rust {
inline namespace cxxbridge1 {
// #include "rust/cxx.h"

struct unsafe_bitcopy_t;

#ifndef CXXBRIDGE1_RUST_STRING
#define CXXBRIDGE1_RUST_STRING
class String final {
public:
  String() noexcept;
  String(const String &) noexcept;
  String(String &&) noexcept;
  ~String() noexcept;

  String(const std::string &);
  String(const char *);
  String(const char *, std::size_t);
  String(const char16_t *);
  String(const char16_t *, std::size_t);
#ifdef __cpp_char8_t
  String(const char8_t *s);
  String(const char8_t *s, std::size_t len);
#endif

  static String lossy(const std::string &) noexcept;
  static String lossy(const char *) noexcept;
  static String lossy(const char *, std::size_t) noexcept;
  static String lossy(const char16_t *) noexcept;
  static String lossy(const char16_t *, std::size_t) noexcept;

  String &operator=(const String &) & noexcept;
  String &operator=(String &&) & noexcept;

  explicit operator std::string() const;

  const char *data() const noexcept;
  std::size_t size() const noexcept;
  std::size_t length() const noexcept;
  bool empty() const noexcept;

  const char *c_str() noexcept;

  std::size_t capacity() const noexcept;
  void reserve(size_t new_cap) noexcept;

  using iterator = char *;
  iterator begin() noexcept;
  iterator end() noexcept;

  using const_iterator = const char *;
  const_iterator begin() const noexcept;
  const_iterator end() const noexcept;
  const_iterator cbegin() const noexcept;
  const_iterator cend() const noexcept;

  bool operator==(const String &) const noexcept;
  bool operator!=(const String &) const noexcept;
  bool operator<(const String &) const noexcept;
  bool operator<=(const String &) const noexcept;
  bool operator>(const String &) const noexcept;
  bool operator>=(const String &) const noexcept;

  void swap(String &) noexcept;

  String(unsafe_bitcopy_t, const String &) noexcept;

private:
  struct lossy_t;
  String(lossy_t, const char *, std::size_t) noexcept;
  String(lossy_t, const char16_t *, std::size_t) noexcept;
  friend void swap(String &lhs, String &rhs) noexcept { lhs.swap(rhs); }

  std::array<std::uintptr_t, 3> repr;
};
#endif // CXXBRIDGE1_RUST_STRING

#ifndef CXXBRIDGE1_RUST_BITCOPY_T
#define CXXBRIDGE1_RUST_BITCOPY_T
struct unsafe_bitcopy_t final {
  explicit unsafe_bitcopy_t() = default;
};
#endif // CXXBRIDGE1_RUST_BITCOPY_T

#ifndef CXXBRIDGE1_RUST_BITCOPY
#define CXXBRIDGE1_RUST_BITCOPY
constexpr unsafe_bitcopy_t unsafe_bitcopy{};
#endif // CXXBRIDGE1_RUST_BITCOPY
} // namespace cxxbridge1
} // namespace rust

using vtkTextActor = ::vtkTextActor;
using vtkTextProperty = ::vtkTextProperty;
using vtkRenderWindow = ::vtkRenderWindow;

extern "C" {
::vtkTextActor *cxxbridge1$192$text_actor_new() noexcept {
  ::vtkTextActor *(*text_actor_new$)() = ::text_actor_new;
  return text_actor_new$();
}

void cxxbridge1$192$text_actor_delete(::vtkTextActor &actor) noexcept {
  void (*text_actor_delete$)(::vtkTextActor &) = ::text_actor_delete;
  text_actor_delete$(actor);
}

void cxxbridge1$192$text_actor_set_input(::vtkTextActor &actor, ::rust::String const *text) noexcept {
  void (*text_actor_set_input$)(::vtkTextActor &, ::rust::String) = ::text_actor_set_input;
  text_actor_set_input$(actor, ::rust::String(::rust::unsafe_bitcopy, *text));
}

void cxxbridge1$192$text_actor_get_input(::vtkTextActor &actor, ::rust::String *return$) noexcept {
  ::rust::String (*text_actor_get_input$)(::vtkTextActor &) = ::text_actor_get_input;
  new (return$) ::rust::String(text_actor_get_input$(actor));
}

void cxxbridge1$192$text_actor_set_position(::vtkTextActor &actor, double x, double y) noexcept {
  void (*text_actor_set_position$)(::vtkTextActor &, double, double) = ::text_actor_set_position;
  text_actor_set_position$(actor, x, y);
}

void cxxbridge1$192$text_actor_get_position(::vtkTextActor &actor, double &x, double &y) noexcept {
  void (*text_actor_get_position$)(::vtkTextActor &, double &, double &) = ::text_actor_get_position;
  text_actor_get_position$(actor, x, y);
}

void cxxbridge1$192$text_actor_set_position2(::vtkTextActor &actor, double x, double y) noexcept {
  void (*text_actor_set_position2$)(::vtkTextActor &, double, double) = ::text_actor_set_position2;
  text_actor_set_position2$(actor, x, y);
}

void cxxbridge1$192$text_actor_get_position2(::vtkTextActor &actor, double &x, double &y) noexcept {
  void (*text_actor_get_position2$)(::vtkTextActor &, double &, double &) = ::text_actor_get_position2;
  text_actor_get_position2$(actor, x, y);
}

::vtkTextProperty *cxxbridge1$192$text_actor_get_text_property(::vtkTextActor &actor) noexcept {
  ::vtkTextProperty *(*text_actor_get_text_property$)(::vtkTextActor &) = ::text_actor_get_text_property;
  return text_actor_get_text_property$(actor);
}

void cxxbridge1$192$text_actor_set_visibility(::vtkTextActor &actor, bool visible) noexcept {
  void (*text_actor_set_visibility$)(::vtkTextActor &, bool) = ::text_actor_set_visibility;
  text_actor_set_visibility$(actor, visible);
}

bool cxxbridge1$192$text_actor_get_visibility(::vtkTextActor &actor) noexcept {
  bool (*text_actor_get_visibility$)(::vtkTextActor &) = ::text_actor_get_visibility;
  return text_actor_get_visibility$(actor);
}

void cxxbridge1$192$text_property_set_font_size(::vtkTextProperty &prop, ::std::int32_t size) noexcept {
  void (*text_property_set_font_size$)(::vtkTextProperty &, ::std::int32_t) = ::text_property_set_font_size;
  text_property_set_font_size$(prop, size);
}

::std::int32_t cxxbridge1$192$text_property_get_font_size(::vtkTextProperty &prop) noexcept {
  ::std::int32_t (*text_property_get_font_size$)(::vtkTextProperty &) = ::text_property_get_font_size;
  return text_property_get_font_size$(prop);
}

void cxxbridge1$192$text_property_set_color(::vtkTextProperty &prop, double r, double g, double b) noexcept {
  void (*text_property_set_color$)(::vtkTextProperty &, double, double, double) = ::text_property_set_color;
  text_property_set_color$(prop, r, g, b);
}

void cxxbridge1$192$text_property_get_color(::vtkTextProperty &prop, double &r, double &g, double &b) noexcept {
  void (*text_property_get_color$)(::vtkTextProperty &, double &, double &, double &) = ::text_property_get_color;
  text_property_get_color$(prop, r, g, b);
}

void cxxbridge1$192$text_property_set_opacity(::vtkTextProperty &prop, double opacity) noexcept {
  void (*text_property_set_opacity$)(::vtkTextProperty &, double) = ::text_property_set_opacity;
  text_property_set_opacity$(prop, opacity);
}

double cxxbridge1$192$text_property_get_opacity(::vtkTextProperty &prop) noexcept {
  double (*text_property_get_opacity$)(::vtkTextProperty &) = ::text_property_get_opacity;
  return text_property_get_opacity$(prop);
}

void cxxbridge1$192$text_property_set_bold(::vtkTextProperty &prop, bool bold) noexcept {
  void (*text_property_set_bold$)(::vtkTextProperty &, bool) = ::text_property_set_bold;
  text_property_set_bold$(prop, bold);
}

bool cxxbridge1$192$text_property_get_bold(::vtkTextProperty &prop) noexcept {
  bool (*text_property_get_bold$)(::vtkTextProperty &) = ::text_property_get_bold;
  return text_property_get_bold$(prop);
}

void cxxbridge1$192$text_property_set_italic(::vtkTextProperty &prop, bool italic) noexcept {
  void (*text_property_set_italic$)(::vtkTextProperty &, bool) = ::text_property_set_italic;
  text_property_set_italic$(prop, italic);
}

bool cxxbridge1$192$text_property_get_italic(::vtkTextProperty &prop) noexcept {
  bool (*text_property_get_italic$)(::vtkTextProperty &) = ::text_property_get_italic;
  return text_property_get_italic$(prop);
}

void cxxbridge1$192$text_property_set_font_family_to_arial(::vtkTextProperty &prop) noexcept {
  void (*text_property_set_font_family_to_arial$)(::vtkTextProperty &) = ::text_property_set_font_family_to_arial;
  text_property_set_font_family_to_arial$(prop);
}

void cxxbridge1$192$text_property_set_font_family_to_courier(::vtkTextProperty &prop) noexcept {
  void (*text_property_set_font_family_to_courier$)(::vtkTextProperty &) = ::text_property_set_font_family_to_courier;
  text_property_set_font_family_to_courier$(prop);
}

void cxxbridge1$192$text_property_set_font_family_to_times(::vtkTextProperty &prop) noexcept {
  void (*text_property_set_font_family_to_times$)(::vtkTextProperty &) = ::text_property_set_font_family_to_times;
  text_property_set_font_family_to_times$(prop);
}

void cxxbridge1$192$text_property_set_justification_to_left(::vtkTextProperty &prop) noexcept {
  void (*text_property_set_justification_to_left$)(::vtkTextProperty &) = ::text_property_set_justification_to_left;
  text_property_set_justification_to_left$(prop);
}

void cxxbridge1$192$text_property_set_justification_to_centered(::vtkTextProperty &prop) noexcept {
  void (*text_property_set_justification_to_centered$)(::vtkTextProperty &) = ::text_property_set_justification_to_centered;
  text_property_set_justification_to_centered$(prop);
}

void cxxbridge1$192$text_property_set_justification_to_right(::vtkTextProperty &prop) noexcept {
  void (*text_property_set_justification_to_right$)(::vtkTextProperty &) = ::text_property_set_justification_to_right;
  text_property_set_justification_to_right$(prop);
}

void cxxbridge1$192$text_property_set_vertical_justification_to_bottom(::vtkTextProperty &prop) noexcept {
  void (*text_property_set_vertical_justification_to_bottom$)(::vtkTextProperty &) = ::text_property_set_vertical_justification_to_bottom;
  text_property_set_vertical_justification_to_bottom$(prop);
}

void cxxbridge1$192$text_property_set_vertical_justification_to_centered(::vtkTextProperty &prop) noexcept {
  void (*text_property_set_vertical_justification_to_centered$)(::vtkTextProperty &) = ::text_property_set_vertical_justification_to_centered;
  text_property_set_vertical_justification_to_centered$(prop);
}

void cxxbridge1$192$text_property_set_vertical_justification_to_top(::vtkTextProperty &prop) noexcept {
  void (*text_property_set_vertical_justification_to_top$)(::vtkTextProperty &) = ::text_property_set_vertical_justification_to_top;
  text_property_set_vertical_justification_to_top$(prop);
}

void cxxbridge1$192$render_window_get_size(::vtkRenderWindow &window, ::std::int32_t &width, ::std::int32_t &height) noexcept {
  void (*render_window_get_size$)(::vtkRenderWindow &, ::std::int32_t &, ::std::int32_t &) = ::render_window_get_size;
  render_window_get_size$(window, width, height);
}
} // extern "C"