// AUTO-GENERATED BY cxxbridge
#include "vtk_data_set_mapper.h"
#include "vtk_mapper.h"
#include "vtk_algorithm_output.h"

#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wmissing-declarations"
#ifdef __clang__
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#endif // __clang__
#endif // __GNUC__

using vtkDataSetMapper = ::vtkDataSetMapper;
using vtkMapper = ::vtkMapper;
using vtkDataSet = ::vtkDataSet;
using vtkAlgorithmOutput = ::vtkAlgorithmOutput;

extern "C" {
::vtkDataSetMapper *cxxbridge1$192$vtk_data_set_mapper_new() noexcept {
  ::vtkDataSetMapper *(*vtk_data_set_mapper_new$)() = ::vtk_data_set_mapper_new;
  return vtk_data_set_mapper_new$();
}

void cxxbridge1$192$vtk_data_set_mapper_delete(::vtkDataSetMapper &mapper) noexcept {
  void (*vtk_data_set_mapper_delete$)(::vtkDataSetMapper &) = ::vtk_data_set_mapper_delete;
  vtk_data_set_mapper_delete$(mapper);
}

void cxxbridge1$192$data_set_mapper_set_input_connection(::vtkDataSetMapper &mapper, ::vtkAlgorithmOutput *output) noexcept {
  void (*data_set_mapper_set_input_connection$)(::vtkDataSetMapper &, ::vtkAlgorithmOutput *) = ::data_set_mapper_set_input_connection;
  data_set_mapper_set_input_connection$(mapper, output);
}

void cxxbridge1$192$data_set_mapper_set_input_data(::vtkDataSetMapper &mapper, ::vtkDataSet *data_set) noexcept {
  void (*data_set_mapper_set_input_data$)(::vtkDataSetMapper &, ::vtkDataSet *) = ::data_set_mapper_set_input_data;
  data_set_mapper_set_input_data$(mapper, data_set);
}
} // extern "C"